### ISSUE TITLE
Configure bundle to use two accounts

### ISSUE THREAD

**Issue by SarramegnaG** [lexik/LexikPayboxBundle#89]
Greetings,

I successfully used your bundle to implement payment features for my website but I will face soon an issue where I have to configure two different Paybox accounts.
In my case, I will have to redirect the user to an account to pay books, and another account to pay courses. But it looks like your bundle only handle one account.

I was thinking about implementing this as they did in [CsaGuzzleBundle](https://github.com/csarrazi/CsaGuzzleBundle) to [use multiple guzzle clients](https://github.com/csarrazi/CsaGuzzleBundle/blob/2.x/src/Resources/doc/clients.md).
Something like this :
```yml
lexik_paybox:
    accounts:
        books:
            parameters:
                production: false        # Switches between Paybox test and production servers (preprod-tpe <> tpe)
                site:        '9999998'   # Site number provided by the bank
                rank:        '98'        # Rank number provided by the bank
                login:       '999999998' # Customer's login provided by Paybox
                hmac:
                    key: 'FEDCBA...43210' # Key used to compute the hmac hash, provided by Paybox
        courses:
            parameters:
                production: false        # Switches between Paybox test and production servers (preprod-tpe <> tpe)
                site:        '9999999'   # Site number provided by the bank
                rank:        '99'        # Rank number provided by the bank
                login:       '999999999' # Customer's login provided by Paybox
                hmac:
                    key: '01234...BCDEF' # Key used to compute the hmac hash, provided by Paybox
```

Any chance you would have any tips to implement this ? I will gracefully offer a pull request when finished ;)

Regards,

Guillaume SARRAMEGNA
